### ISSUE TITLE
TypeError: Not a buffer error in token.js

### ISSUE THREAD

**Issue by roberthan1992** [pusher/pusher-http-node#11]
Hi, we're seeing an error with the latest version of Pusher - this happens when we do a Pusher.trigger on a public channel. It seems do have something to do with the changes in token.js. 

    TypeError: Not a buffer
    at new Hmac (crypto.js:257:17)
    at Object.Hmac (crypto.js:255:12)
    at Token.sign (/Users/rhan/Projects/hgapp/node_modules/pusher/lib/token.js:22:17)
    at createSignedQueryString (/Users/rhan/Projects/hgapp/node_modules/pusher/lib/requests.js:69:45)
    at Object.send (/Users/rhan/Projects/hgapp/node_modules/pusher/lib/requests.js:20:21)
    at Pusher.post (/Users/rhan/Projects/hgapp/node_modules/pusher/lib/pusher.js:155:12)
    at Object.trigger (/Users/rhan/Projects/hgapp/node_modules/pusher/lib/events.js:10:10)
    at Pusher.trigger (/Users/rhan/Projects/hgapp/node_modules/pusher/lib/pusher.js:138:10)
    at PerformCardUpdated (/Users/rhan/Projects/hgapp/hgnode/util/PusherManager.js:207:23)
    at /Users/rhan/Projects/hgapp/hgnode/services/PerformanceService.js:2332:31

**Comment by roberthan1992** [comment]
Sorry, please disregard - the pusher secret was not being set.

**Comment by zimbatm** [comment]
I think it's legitimate. An explicit "secret is missing" error should have been raised instead of that.

**Comment by leggetter** [comment]
This will be fixed by f7680a7835a3d0ac09a46c44bda067761c172260 and d7eb8c94da5f146a326cf2bd0efd3a57f8e9fdd1

**Comment by zimbatm** [comment]
Thanks, looking good

**Comment by srt32** [comment]
f7680a7 and d7eb8c9 are both merged. Can this issue be closeD?
