### ISSUE TITLE
Crash on get request (node 12.x)

### ISSUE THREAD

**Issue by 74nk** [pusher/pusher-http-node#12]
```
_http_outgoing.js:333
    throw new Error('"name" and "value" are required for setHeader().');
          ^
Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at Request.start (c:\gdrive\dev\townsquared\trunk\server\notifications\node_modules\pusher\node_modules\request\request.js:812:30)
    at Request.end (c:\gdrive\dev\townsquared\trunk\server\notifications\node_modules\pusher\node_modules\request\request.js:1494:28)
    at end (c:\gdrive\dev\townsquared\trunk\server\notifications\node_modules\pusher\node_modules\request\request.js:550:16)
    at c:\gdrive\dev\townsquared\trunk\server\notifications\node_modules\pusher\node_modules\request\request.js:564:9
    at process._tickDomainCallback (node.js:381:11)
```
Bug is there:
```
 /lib/requests.js

  handler[options.method.toLowerCase()]({
    url: url,
    proxy: config.proxy,
    timeout: config.timeout,
    headers: {
      // in case 'content-type' is undefined request.setHeader() will crash app
      'content-type': (body ? 'application/json' : undefined) 
    },
    body: body
  }, function(err, res, resBody) {
    dispatchRequestResult(err, url, this.req, res, callback);
  });
```
This is fixed version:

```
	var params = {
		url: url,
		proxy: config.proxy,
		timeout: config.timeout
	};

	if (body) {
		params.headers = {'content-type': 'application/json'};
		params.body = body;
	}

	handler[options.method.toLowerCase()](params, function(err, res, resBody) {
		dispatchRequestResult(err, url, this.req, res, callback);
	});
```

**Comment by zimbatm** [comment]
Fixed in v1.0.6
