### ISSUE TITLE
passing a callback to the trigger function causes an error

### ISSUE THREAD

**Issue by mypark** [pusher/pusher-http-node#20]
using the trigger function with a callback throw an error

```
Error: Invalid socket id: 'function (err) {
                console.log(err);
                done(err);
            }'
      at validateSocketId /node_modules/pusher/lib/pusher.js:24:11)
      at Pusher.trigger (/node_modules/pusher/lib/pusher.js:123:5)
```
```
          pusher.trigger('test_channel', 'my_event', {
                "message": "hello world"
            }, function(err){
                console.log(err);
                done(err);
            });
```

**Comment by mypark** [comment]
ok I see now, I'm not passing in the optional socketId that is causing the error.
